name: Create release candidate PR

on:
  - pull_request
  - workflow_dispatch

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - run: echo 'doing release thing'
      - name: test exit
        shell: bash
        if: 1 == 2
        run: |
          echo 'oiasdjf'
          exit 0
      - run: echo value=$(test ${{ github.event_name }} != workflow_dispatch && echo true || echo false) >> "$GITHUB_OUTPUT"
        id: is-workflow
      - run: echo ${{ steps.is-workflow.outputs.value }}
