name: Create release candidate PR

on:
# schedule:
#   - cron: '* * * * *'
 workflow_dispatch:
 pull_request:


jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - run: echo 'doing release thing'
      - name: test exit
        shell: bash
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo ${{ github.event_name }}
          echo 'oiasdjf'
          exit 0
      - run: echo value=$(test ${{ github.event_name }} != schedule && echo true || echo false) >> "$GITHUB_OUTPUT"
        id: is-workflow
      - run: echo ${{ steps.is-workflow.outputs.value }}
